apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: key-generator
    version: "1.0"
  name: key-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: key-generator
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
