apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: url
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /url
    route:
      - destination:
          port:
            number: 80
          host: url.default.svc.cluster.local
  gateways:
  - microservice-gateway