spring:
  application:
    name: url
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

infrastructure:
  upstream-service:
    key-generator:
      host: 127.0.0.1
      port: 8081