spring:
  application:
    name: key-generator
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

infrastructure:
  upstream-service:
    mongodb:
      host: 127.0.0.1
      port: 27017
      user: admin
      password: admin
      db: url